name: Node.js CI

on:
  push:
    branches: [master]

permissions:
  checks: write

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@5.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: server
        run: npm ci
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}


      - name: Run linter
        working-directory: server
        run: npm run lint

      # TODO, Add the tests when time permits (using docker or dind with the
      # existing compose, or create a new one)
      # - name: Run tests
      #   working-directory: server
      #   run: npm run test

      # - name: Publish Test Report
      #   uses: mikepenz/action-junit-report@v5
      #   if: success() || failure() # always run even if the previous step fails
      #   with:
      #     report_paths: 'server/__tests__/junit.xml'
